steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args: [ '-c', 'docker pull ${_IMAGE}:latest || exit 0' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_IMAGE}:${_TAG}', '--cache-from', '${_IMAGE}:latest', '.' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'tag', '${_IMAGE}:${_TAG}', '${_IMAGE}:latest' ]
timeout: 600s
options:
  substitution_option: ALLOW_LOOSE
tags: [ '${_BUILD_TAG_1}', '${_BUILD_TAG_2}' ]
images: [ '${_IMAGE}:${_TAG}', '${_IMAGE}:latest' ]
